test01/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get(
    '/',
    function () {
        return view('welcome');
    }
);

Route::resource('/article', 'ArticleController');

Route::get('/search', 'ArticleController@searchArticle')->name('article.searchArticle');

test01/app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $table = 'article';

    protected $fillable = [
        'title',
        'content',
        'view',
        'url_image'
    ];
}

test01/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

test01/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

test01/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Contracts\ArticleServiceContract as ArticleService;

class ArticleController extends Controller
{
    public function __construct(ArticleService $articleService) {
        $this->articleService = $articleService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = $this->articleService->getAllArticles();
        return view('article.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $updateView = $this->articleService->updateView($id);
        $articlesById = $this->articleService->getArticleById($id);
        $articles = $this->articleService->getAllArticles();
        return view('article.detail', [
            'articlesById' => $articlesById,
            'articles' => $articles,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function searchArticle(Request $request)
    {
        $input = $request->all();
        $keySearch = $input['key'];
        if (!is_null($input['key'])) {
            $search = $this->articleService->getSearch($input);
        } else {
            return redirect()->route('article.index');
        }
        return view('article.search', [
            'search' => $search,
            'keySearch' => $keySearch,
        ]);
    }
}

test01/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

test01/resources/views/article/detail.blade.php
@extends('layout.admin_layout')
@section('main_content')
    <div class="row mt-4">
        <div class="col-lg-8">
            <article>
                <header class="mb-4">
                    <h1 class="fw-bolder mb-1">{{ $articlesById->title }}</h1>
                    <div class="row mb-4">
                        <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($articlesById->created_at)) }}</span> </div>
                        <div class="col"> <i class="far fa-eye"></i> <span>{{ $articlesById->view }}</span> </div>
                        <div class="col"> <i class="far fa-heart tym"></i> <span id="count"></span></div>
                    </div>
                </header>
                <figure class="mb-4"><img class="img-fluid rounded" src="{{ $articlesById->url_image }}" alt="{{ $articlesById->title }}" /></figure>
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{ $articlesById->content }}</p>
                </section>
            </article>
        </div>
        <div class="col-lg-4">
            @foreach ($articles as $key => $article)
                <div class="card mb-4">
                    <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top height_200" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                            <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                        </div>
                        <h2 class="card-title h3">{{ $article->title }}</h2>
                        <p class="card-text">{{ $article->content }}</p>
                        <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                    </div>
                </div>
            @endforeach
            <div class="pagination justify-content-center">
                {{ $articles->links('pagination::bootstrap-4') }}
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ mix('js/likeArticle.js') }}"></script>
@endsection

test01/resources/views/article/index.blade.php
@extends('layout.admin_layout')
@section('main_content')
    <div class="row mt-4">
        <h1 class="fw-bolder mb-4 text-center">Danh sách bài viết</h1>
        <div class="col-lg-8">
            @foreach ($articles as $key => $article)
                @if ($key==0)
                    <div class="card mb-4">
                        <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                        <div class="card-body">
                            <div class="row mb-4">
                                <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                                <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                            </div>
                            <h2 class="card-title">{{ $article->title }}</h2>
                            <p class="card-text">{{ $article->content }}</p>
                            <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                        </div>
                    </div>
                @endif

                @if ($key%2==0 & $key!=0 & $key!=1 & $key!=2)
                    <div class="row mt-4 mb-4">
                        <div class="col">
                            <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top height_200" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                        </div>
                        <div class="col">
                            <h2 class="card-title h3">{{ $article->title }}</h2>
                            <div class="row mb-4">
                                <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                                <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                            </div>
                            <p class="card-text">{{ $article->content }}</p>
                            <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                        </div>
                    </div>
                    <hr class="my-0" />
                @endif

                @if ($key%2!=0 & $key!=0 & $key!=1 & $key!=2)
                    <div class="row mt-4 mb-4">
                        <div class="col">
                            <h2 class="card-title h3">{{ $article->title }}</h2>
                            <div class="row mb-4">
                                <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                                <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                            </div>
                            <p class="card-text">{{ $article->content }}</p>
                            <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                        </div>
                        <div class="col">
                            <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top height_200" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                        </div>
                    </div>
                    <hr class="my-0" />
                @endif
            @endforeach
            
            <div class="pagination mt-4 justify-content-center">
                {{ $articles->links('pagination::bootstrap-4') }}
            </div>

            <div class="text-right">
                <div class="d-inline-block"></div>
            </div>
        </div>
        <div class="col-lg-4">
            @foreach ($articles as $key => $article)
                @if ($key==1)
                    <div class="card mb-4">
                        <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top height_200" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                        <div class="card-body">
                            <div class="row mb-4">
                                <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                                <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                            </div>
                            <h2 class="card-title h3">{{ $article->title }}</h2>
                            <p class="card-text">{{ $article->content }}</p>
                            <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                        </div>
                    </div>
                @endif

                @if ($key==2)
                    <div class="card mb-4">
                        <a href="{{ route('article.show', [$article->id]) }}"><img class="card-img-top height_200" src="{{ $article->url_image }}" alt="{{ $article->title }}" /></a>
                        <div class="card-body">
                            <div class="row mb-4">
                                <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($article->created_at)) }}</span> </div>
                                <div class="col"> <i class="far fa-eye"></i> <span>{{ $article->view }}</span> </div>
                            </div>
                            <h2 class="card-title h3">{{ $article->title }}</h2>
                            <p class="card-text">{{ $article->content }}</p>
                            <a class="btn btn-success" href="{{ route('article.show', [$article->id]) }}">Read more →</a>
                        </div>
                    </div>
                @endif
            @endforeach
        </div>
    </div>
@endsection

test01/resources/views/article/search.blade.php
@extends('layout.admin_layout')
@section('main_content')
    {{-- <div class="container"></div> --}}
        <div class="row mt-4 height_800">
            <h4 class="mt-4"> {{ $search->total() }} Kết quả tìm kiếm cho: " {{ $keySearch }}" </h4>

            @foreach ($search as $key => $value)
                <div class="row mt-4 mb-4">
                    <div class="col">
                        <h2 class="card-title h3">{{ $value->title }}</h2>
                        <div class="row mb-4">
                            <div class="col"> <i class="far fa-clock"></i> <span>{{ date('d/m/Y', strtotime($value->created_at)) }}</span> </div>
                            <div class="col"> <i class="far fa-eye"></i> <span>{{ $value->view }}</span> </div>
                        </div>
                        <p class="card-text">{{ $value->content }}</p>
                        <a class="btn btn-success" href="{{ route('article.show', [$value->id]) }}">Read more →</a>
                    </div>
                    <div class="col">
                        <a href="{{ route('article.show', [$value->id]) }}"><img class="card-img-top height_200" src="{{ $value->url_image }}" alt="{{ $value->title }}" /></a>
                    </div>
                </div>
                <hr class="my-0" />
            @endforeach
            <div class="pagination mt-4 justify-content-center">
                {{ $search->appends(['key' => $keySearch])->links('pagination::bootstrap-4') }}
            </div>
        </div>
@endsection

test01/resources/views/layout/admin_layout.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>post</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{asset('backend/css/styles.css')}}" rel="stylesheet" />

        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

        <link rel="stylesheet" href="{{asset('/css/admin.css')}}" type="text/css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <!-- Responsive navbar-->
        @include('layout.navbar')

        <!-- Page content-->
        <div class="container">
            @yield('main_content')
        </div>

        <!-- Footer-->
        @include('layout.footer')

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{asset('backend/js/scripts.js')}}"></script>
        @yield('js')
    </body>
</html>

test01/resources/views/layout/footer.blade.php
<footer class="py-5 bg-success">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>

test01/resources/views/layout/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container justify-content-start">
        <a class="navbar-brand" href="/article"><i class="fas fa-home"></i></a>

        <div class="col-10">
            <form role="search" method="GET" id="formSearchTask" action="{{route('article.searchArticle')}}" enctype="multipart/form-data">
                <div class="input-group">
                    <input type="text" name="key" class="form-control" id="key_search" placeholder="Search Article">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit" id="btn_search">
                            <i class="fas fa-search text-white"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</nav>